# Generated by Django 4.2.7 on 2023-11-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(null=True, to='note.tag'),
        ),
    ]
